version: '3.3'

services:
  db:
    ports: 
      - 5432:5432
    secrets:
      - postgres_user
      - postgres_password
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password

secrets:
   postgres_user:
     file: ./postgres_fake_user
   postgres_password:
     file: ./postgres_fake_password
